### ISSUE TITLE
Infinite loop when file is not playable

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#93] opened 2018-11-07 07:15 UTC
I just added 3 files to the standard playlist component and wanted to play the first, but it got instantly stuck infinitely looping and spamming the log to death:
```
12:21.573 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Courtesy
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Courtesy.mp3
03:13
12:21.573 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Focus
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Focus.mp3
02:42
12:21.573 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Otis
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Otis.mp3
02:36
12:21.574 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Courtesy
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Courtesy.mp3
03:13
12:21.574 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Focus
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Focus.mp3
02:42
12:21.574 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Otis
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Otis.mp3
02:36
12:21.574 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Courtesy
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Courtesy.mp3
03:13
12:21.574 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Focus
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Focus.mp3
02:42
12:21.574 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Otis
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Otis.mp3
02:36
12:21.574 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Courtesy
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Courtesy.mp3
03:13
12:21.575 I [JavaFX Applicat] GeneralPlayer - Player sp.it.pl.audio.playback.VlcPlayer@43a92bd3 can not play item Chipzel - Focus
file:/home/janek/daten/musik/Chipzel%20-%20Super%20Hexagon%20EP/Chipzel%20-%20Focus.mp3
02:42
```

**Comment by sghpjuikit** [comment] 2018-11-07 19:14
Regression. I'll look into it soon.

**Comment by sghpjuikit** [comment] 2019-02-05 15:58
Duplicate of #35

**Closed by sghpjuikit** 2019-02-05 15:58 UTC
