### ISSUE TITLE
Serializing and deserializing windows fails sometimes

### ISSUE THREAD

**Issue by Xerus2000** [sghpjuikit/player#59] opened 2018-03-03 13:08 UTC
```
58:38.151 I [JavaFX Applicat] WindowManager - Serializing 1 application windows
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7c70e50fb2, pid=12765, tid=12824
#
# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.4+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.4+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjimage.so+0x3fb2]  ImageStrings::find(Endian*, char const*, int*, unsigned int)+0x42
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/janek/Projects/PlayerFX/working dir/core.12765)
```

Unfortunately I can't reproduce the issue. When it happens again I will leave more details. Furthermore sometimes deserialization failed resulting in the application not even opening, so i think there needs to be more error catching.

**Comment by sghpjuikit** [comment] 2018-03-03 14:40
What you provided is unfortunately an internal JVM crash, not something you can fix with catching an exception. I have never experienced this, so I'll need more information - when this happens and so on, preferably exact steps to reproduce the issue.

**Comment by Xerus2000** [comment] 2018-04-06 00:48
Okay I just ran the project as-is on my machine, I couldn't scroll horizontally, there were no playerControls since compilation failed. Then, on exit, the crash:
[hs_err_pid4777.log](https://github.com/sghpjuikit/player/files/1882278/hs_err_pid4777.log)

Logs:
[log_contents.log](https://github.com/sghpjuikit/player/files/1882280/log_contents.log)
```
43:33.895 I [JavaFX Applicat] Player - Next item metadata cache copy failed - content does not correspond to correct item. Loading now...
43:34.313 I [JavaFX Applicat] Player - Pre-loading metadata for next item to play.
43:44.326 I [JavaFX Applicat] Action - Executing action Open settings
43:54.904 I [JavaFX Applicat] Widget - Widget=FunctionViewer closing
44:14.269 I [JavaFX Applicat] Window - Closing main window. 1 windows currently open.
44:14.281 I [JavaFX Applicat] WindowManager - Serializing 1 application windows
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f3d36f57d44, pid=4777, tid=4777
#
# JRE version: Java(TM) SE Runtime Environment (9.0+11) (build 9.0.4+11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (9.0.4+11, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0x9d44]  pthread_mutex_lock+0x4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/janek/Daten/Projects/player/working dir/core.4777)
#
# An error report file with more information is saved as:
# /home/janek/Daten/Projects/player/working dir/hs_err_pid4777.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

**Comment by sghpjuikit** [comment] 2018-04-06 16:29
Problem is definitely outside of our scope of influence. This needs to be reproducible to trace the root cause. Window serialization is using XStream library, that serializes a small data class representing the state of the window. A good start. I however do not remember ever encountering this problem.

**Comment by Xerus2000** [comment] 2018-04-08 17:32
Maybe it was because of the missing classes?

**Comment by sghpjuikit** [comment] 2018-04-09 16:36
I remember such problem in the past, it is indeed possible. I will investigate.

**Comment by sghpjuikit** [comment] 2019-01-12 13:37
Is this issue gone or do you still experience it?

**Comment by sghpjuikit** [comment] 2019-06-24 23:04
This should no longer be an issue. Of course, if the underlying data classes change, deserialization will fail, but there is little to be done about that except error handling and supporting class evolution (which is not worth at the moment, since it requires wholly new serialization format). Closing.

**Closed by sghpjuikit** 2019-06-24 23:04 UTC
Labels: bug

**Comment by sghpjuikit** [comment] 2019-06-24 23:07
See #155
