### ISSUE TITLE
Segfault during startup

### ISSUE THREAD

**Issue by xeruf** [sghpjuikit/player#182] opened 2020-05-14 11:42 UTC
```
18:11.615 I [           io-4] WindowManager - Deserializing windows.
18:11.616 I [           io-4] WindowManager - Deserialized 0/0 windows.
18:11.616 I [JavaFX Applicat] PlayerManager - Restoring last playback state...
18:11.617 I [JavaFX Applicat] PlayerManager -     aborted: no playback was active
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2672b5bfa0, pid=21456, tid=21483
#
# JRE version: OpenJDK Runtime Environment 
(Zulu12.3+11-CA) (12.0.2+3) (build 12.0.2+3)
# Java VM: OpenJDK 64-Bit Server VM (12.0.2+3, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libpthread.so.0+0x9fa0]  pthread_mutex_lock+0x0
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/janek/daten/projects/ngmp/player/app/hs_err_pid21456.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
[hs_err_pid21456.log](https://github.com/sghpjuikit/player/files/4628013/hs_err_pid21456.log)

**Comment by sghpjuikit** [comment] 2020-05-16 14:54
@xerus2000, you always give me headaches.

This is probably not Zulu JDK specific. Nor Linux distro specific. Exact same issue (failing native createWindow()) on Debian: https://pastebin.com/wNHhKt0E

Rather, it looks like a JavaFX-gtk bug. As far as I know this gtk thing has various versions and lvl of support in different distros/applications and I believe JavaFX moved/supported gtk3 at some point and it caused issues. https://github.com/javafxports/openjdk-jfx/issues?q=gtk

 What platform is this on? Kde neon? What gtk version do you have?

For some info about the effort behind gtk2/3 support: https://bugs.openjdk.java.net/browse/JDK-8087516

This means you can specify which gtk the application should run with. Gtk2 may still be used by default, but that may be old info.

Pls try to launch with `-Djdk.gtk.version=3` or `-Djdk.gtk.version=2`. Any changes?

**Comment by xerus2000** [comment] 2020-05-17 10:43
Nope, changes nothing - but I doubt that these are actually ending up in the JVM

**Comment by sghpjuikit** [comment] 2020-05-17 14:07
I'll try setting up your OS in a VM.  But this may be better off being filled as JDK bug report.

**Comment by sghpjuikit** [comment] 2020-05-23 23:41
I'm having issues setting up a VM KDE Neon. I get user installation errors. Will try again, but this is looking grim. Unfortunately you will have to help me help you - this is almost out of my reach to fix.

1 Pls look at the stacktraces when using gtk2/3 whether it actually loads gtk2 or 3 library to confirm the option has an effect. It is important to rule out that gtk version is not the cause of the issue.

2 This issue should affect any JavaFX application with a window. Pls try some other JavaFX application, I have no recommendation as the JavaFX Ensemble may be outdated. It may be best to simply create a new JavaFX project (latest released JavaFX) and run it as is with primary stage. If it works, then try a `new Stage().show()`. If these work we can work from there, but my guess it all of these will result in the same error. You either have too modern system or too cut down one. Or JavaFX does not support it yet, which it should.

**Comment by xerus2000** [comment] 2020-05-24 19:07
I have a JavaFX project myself, it runs fine.

**Comment by sghpjuikit** [comment] 2020-05-30 14:22
I see, thx for the confirmation. There must be something project specific then.

I have managed to obtain/set up a KDE Neon VmWare VM. I may need some help with setting up the development environment, ideally as close to yours as possible. Would you be willing to help me in this regard? This concerns mostly basic OS setup, git, JDK, Idea IDE.

**Comment by xerus2000** [comment] 2020-05-30 16:10
```sh
❯ neofetch && git --version && java -version
             `..---+/---..`                janek@pavilion-neon 
         `---.``   ``   `.---.`            ------------------- 
      .--.`        ``        `-:-.         OS: KDE neon User Edition 5.18 x86_64 
    `:/:     `.----//----.`     :/-        Host: HP Pavilion Power Laptop 15-cb0xx 
   .:.    `---`          `--.`    .:`      Kernel: 5.1.15-050115-generic 
  .:`   `--`                .:-    `:.     Uptime: 5 hours, 11 mins 
 `/    `:.      `.-::-.`      -:`   `/`    Packages: 3390 
 /.    /.     `:++++++++:`     .:    .:    Shell: zsh 5.4.2 
`/    .:     `+++++++++++/      /`   `+`   Resolution: 1920x1080 
/+`   --     .++++++++++++`     :.   .+:   DE: KDE 
`/    .:     `+++++++++++/      /`   `+`   WM: KWin 
 /`    /.     `:++++++++:`     .:    .:    WM Theme: Breeze 
 ./    `:.      `.:::-.`      -:`   `/`    Theme: Breeze Dark [KDE], Breeze [GTK3] 
  .:`   `--`                .:-    `:.     Icons: Breeze [KDE], Breeze [GTK3] 
   .:.    `---`          `--.`    .:`      Terminal: yakuake 
    `:/:     `.----//----.`     :/-        CPU: Intel i5-7300HQ (4) @ 3.500GHz 
      .-:.`        ``        `-:-.         GPU: NVIDIA GeForce GTX 1050 Mobile 
         `---.``   ``   `.---.`            GPU: Intel HD Graphics 630 
             `..---+/---..`                Memory: 9629MiB / 23987MiB 

git version 2.26.2
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

```sh
❯ ls /usr/lib/jvm && /usr/lib/jvm/zulu-12-amd64/bin/java -version
java-1.11.0-openjdk-amd64  java-1.8.0-openjdk-amd64  java-11-openjdk-amd64  java-12-oracle  java-8-openjdk-amd64  java-8-oracle  openjdk-11  zulu-12-amd64
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment Zulu12.3+11-CA (build 12.0.2+3)
OpenJDK 64-Bit Server VM Zulu12.3+11-CA (build 12.0.2+3, mixed mode, sharing)
```

Segfault happens both with `java-12-oracle` and with `zulu-12-amd64` set as jvm in gradle.properties.

**Comment by sghpjuikit** [comment] 2021-08-18 08:59
I'll look into this soon. The project is working fine on WIn 8.1 and Win10 (recently I have done a sufficient run on WIn10 to confirm and fixed few issues discovered there).

**Comment by sghpjuikit** [comment] 2023-08-26 11:30
Closing as outdated. If someone uses the project on Linux and this comes back, I'll have a look

**Closed by sghpjuikit** 2023-08-26 11:30 UTC
